
title: cyberboy666 & user43368831

email: langolierz@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://langolierz.github.io"
#url: "localhost:4000"
github_username:  langolierz


diy-section-image: /images/diy-poster.png
recur-section-image: /images/recur-poster.png
trashpalace-section-image: /images/trashpalace-poster.png
sybersex-section-image: /images/sybersex-poster.png
tablehooters-section-image: /images/tablehooters-poster.png
wemakeporn-section-image: /images/wemakeporn-poster.png
irregular-section-image: /images/irregular-poster.png
cyberboy666-section-image: /images/cyberboy666-poster.png


# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
collections:
    articles: {output: true, permalink: '/:path/'}
exclude:
    - Gemfile
    - Gemfile.lock
include:
    - _pages
