
title: cyberboy666 & user43368831

email: langolierz@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://langolierz.github.io"
#url: "localhost:4000"
github_username:  langolierz


diy-section-image: /images/diy-poster.png
diy-banner-image: /images/diy-banner.jpg
recur-section-image: /images/recur-poster.png
recur-banner-image: /images/recur-banner.jpg
trashpalace-section-image: /images/trashpalace-poster.png
trashpalace-banner-image: /images/trashpalace-banner.jpg
sybersex-section-image: /images/sybersex-poster.png
sybersex-banner-image: /images/sybersex-banner.jpg
tablehooters-section-image: /images/tablehooters-poster.png
tablehooters-banner-image: /images/tablehooters-banner.jpg
wemakeporn-section-image: /images/wemakeporn-poster.png
wemakeporn-banner-image: /images/wemakeporn-banner.jpg
irregular-section-image: /images/irregular-poster.png
irregular-banner-image: /images/irregular-banner.jpg
cyberboy666-section-image: /images/cyberboy666-poster.png
cyberboy666-banner-image: /images/cyberboy666-banner.png


# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
collections:
    articles: {output: true, permalink: '/:path/'}
exclude:
    - Gemfile
    - Gemfile.lock
include:
    - _pages
