# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: cyberboy666 & user43368831
email: langolierz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://langolierz.github.io"
# url: localhost:4000
github_username:  langolierz

diy-title: 'DIY video builds'
diy-section-image: /images/diy-poster.jpg
archive-title: 'video hardware ARCHIVE'
archive-section-image: /images/archive-poster2.jpg
trash-title: 'TRASH palace film club'
trash-section-image: /images/trash-poster.png
other-title: 'about, thoughts & OTHER'
other-section-image: /images/other-poster.jpg


# Build settings
markdown: kramdown
theme: minima
gems:
    - jekyll-feed
collections:
    articles: {output: true, permalink: '/:path/'}
exclude:
    - Gemfile
    - Gemfile.lock
include:
    - _pages
