
title: cyberboy666 & user43368831

email: langolierz@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://langolierz.github.io"
#url: "localhost:4000"
github_username:  langolierz

diy-title: 'DIY video builds'
diy-section-image: /images/diy-poster.png
archive-title: 'video hardware ARCHIVE'
archive-section-image: /images/archive-poster.png
trash-title: 'TRASH palace film club'
trash-section-image: /images/trash-poster.png
other-title: 'about, thoughts & OTHER'
other-section-image: /images/other-poster.png


# Build settings
markdown: kramdown
theme: minima
gems:
    - jekyll-feed
collections:
    articles: {output: true, permalink: '/:path/'}
exclude:
    - Gemfile
    - Gemfile.lock
include:
    - _pages
